Repository naruhiyo/aman, pull requests merged in 2020-12, with the labels that each got.

#35 [AM-59] Update README
  README.md
Labels: documentation

#36 [AM-59] Modify description of aman
  README.md
Labels: documentation

#37 [AM-59] Modify issues link
  README.md
Labels: bug, documentation

#40 [AM-65] Add workflow to publish github release
  .github/workflows/release.yml
  .goreleaser.yml
  go.mod
  go.sum
  implement/io/input.go
  implement/model/man_data_object.go
  implement/pagination/pagination.go
  implement/util/command.go
  implement/window/window.go
  main.go
Labels: enhancement

#45 Fix #44
  implement/util/command.go
  main.go
Labels: bug

#50 Fix #47, #49
  .gitignore
  go.mod
  go.sum
  implement/io/input.go
  implement/util/command.go
  main.go
  struct/io/input.go
Labels: bug

#55 Fix #51, #52, #53
  .github/workflows/release.yml
  README.md
Labels: documentation

#56 Modify README
  README.md
Labels: documentation

#58 Fix #57
  implement/window/window.go
Labels: bug

#60 Fix #59
  implement/model/man_data_object.go
  implement/window/window.go
Labels: enhancement

#61 Update README
  README.md
Labels: documentation

#72 Move .goreleaser.yml to .github/workflows/
  .github/workflows/.goreleaser.yml
  .github/workflows/release.yml
Labels: enhancement
